version: '3.8'

services:
  mysql-test:
    image: mysql:8
    container_name: mysql-test
    ports:
      - "3307:3306"  # 3307 pe local -> 3306 în container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - testnet

volumes:
  mysql_test_data:

networks:
  testnet:
    driver: bridge
